
name: Run lighthouse script and push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # remove this when cron enabled
    if: ${{ !contains(github.event.head_commit.message, 'new reports generated') }}
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: run app
        run: node index.js

      - name: commit to main
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email "kkindorf@trimarkusa.com"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "new reports generated"
          git push origin main
